runtime: python27
api_version: 1
threadsafe: true

- url: .*
  script: main.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: twitter
  version: latest
- name: plotly
  version: latest
- name: pandas
  version: latest
- name: numpy
  version: latest